# Generated by Django 5.0.4 on 2024-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='noreply@example.com', max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=5000)),
            ],
        ),
    ]
