# Generated by Django 5.0.4 on 2024-04-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Help',
        ),
    ]
